### PR TITLE
adding-CODE_OF_CONDUCT.md-updating-CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by geekymehta**
updating CONTRIBUTION.md and adding CODE_OF_CONDUCT.md which is refenrenced in CONTRIBUTION.md

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@geekymehta hey, can you add how a person can pull and clone the repo and start working in it ? also

**Comment by geekymehta** [comment]
ofcourse, but can to tell me where to start.

**Comment by geekymehta** [comment]
Are you suggesting something like this,



To pull and clone a Git repository and get started working with it, you can provide the following instructions:

Step 1: Install Git

If the person doesn't already have Git installed on their computer, they should start by installing it. They can download Git from the official website: [Git Downloads](https://git-scm.com/downloads).

Step 2: Open a Terminal or Command Prompt

The person should open a terminal or command prompt on their computer. On Windows, they can use the Command Prompt or Git Bash (installed with Git). On macOS and Linux, they can use the Terminal.

Step 3: Navigate to the Directory Where They Want to Clone the Repository

Use the cd command to navigate to the directory where they want to clone the repository. For example:

bash
Copy code
cd /path/to/your/directory
Replace /path/to/your/directory with the actual path to the desired directory.

Step 4: Clone the Repository

To clone a Git repository, they can use the git clone command followed by the URL of the repository. For example:

bash
Copy code
git clone https://github.com/username/repo.git
Replace https://github.com/username/repo.git with the URL of the Git repository you want to clone.

Step 5: Configure Git (if needed)

If this is the person's first time using Git on their computer, they may need to configure their name and email. They can do this using the following commands:

bash
Copy code
git config --global user.name "Your Name"
git config --global user.email "youremail@example.com"
Replace "Your Name" and "[youremail@example.com](mailto:youremail@example.com)" with your actual name and email.

Step 6: Start Working

The person can now start working on the repository. They can make changes to the files in the repository, stage those changes, commit them, and push them to the remote repository.

Here are some basic Git commands to get started:

git add .: Stage changes for commit.
git commit -m "Your commit message": Commit staged changes with a message.
git push origin master: Push changes to the remote repository.

**Comment by geekymehta** [comment]
@ojasaklechayt i've appended a step-by-step guide of **how to clone and pull request in CONTRIBUTING.md** here[https://github.com/ojasaklechayt/Music-Streaming-App/pull/3/commits/d943398805ab866b9a2e0b7352cdaa1b7ce5dd3e]

**Pull request merged**
