### PR TITLE
[feat] [client] Adding-toast-notifications

### LINKED ISSUE #18: adding notifications for login and registration api success or error
please assign me this issue with hacktoberfest label, would love to contribute ^^

### PR DESCRIPTION
**Pull request by Sameersawant77**
closes #18 

Added toast notifications for successful login and registration or error while authenticating ^^
npm i to download the toastify node package

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@Sameersawant77 Thankyou for the PR. I would like to add on into it that can you please specify the toster which is been shown. Like if password is not entered, it should display password not display, or if the password is not correct, it can show wrong password added or if email format is not correct then it can show wrong email format etc etc. same goes for the registration page.

**Comment by Sameersawant77** [comment]
Hey @ojasaklechayt, sure i can the requirements provided the API response passes a message depending on the error

**Comment by ojasaklechayt** [comment]
> Hey @ojasaklechayt, sure i can the requirements provided the API response passes a message depending on the error

You can check the backend code, I feel the response for wrong password is not there, may you can add up that condition in the backend.

**Comment by Sameersawant77** [comment]
@ojasaklechayt  I have added toast notifications "user not found" and "invalid password" for login and "User already exists" while signup ^^

**Comment by ojasaklechayt** [comment]
@Sameersawant77 Great work Sameer, Thanks for the contribution ^^^

**Pull request merged**
